INSERT INTO RATING(NAME) VALUES ('G');
INSERT INTO RATING(NAME) VALUES ('PG');
INSERT INTO RATING(NAME) VALUES ('PG-13');
INSERT INTO RATING(NAME) VALUES ('R');
INSERT INTO RATING(NAME) VALUES ('NC-17');

INSERT INTO GENRE(NAME) VALUES ('Комедия');
INSERT INTO GENRE(NAME) VALUES ('Драма');
INSERT INTO GENRE(NAME) VALUES ('Мультфильм');
INSERT INTO GENRE(NAME) VALUES ('Триллер');
INSERT INTO GENRE(NAME) VALUES ('Документальный');
INSERT INTO GENRE(NAME) VALUES ('Боевик');

/*
INSERT INTO FILM (NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
			VALUES ('Джентльмены удачи',
			        'Воспитатель детсада внедряется в банду матерых рецидивистов.
                     Евгений Леонов в разошедшейся на цитаты комедии',
			        '1971-12-13', 84,  1);
INSERT INTO FILM (NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
			VALUES ('Звёздные войны: Эпизод 1 — Скрытая угроза',
			        'У каждой саги есть начало',
			        '1999-05-16', 136,  2);
INSERT INTO FILM (NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
			VALUES ('Гарри Поттер и философский камень',
			        'Путешествие в твою мечту',
			        '2001-11-04', 152,  1);
INSERT INTO FILM (NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
			VALUES ('Любовь и голуби',
			        'Вася пытается заслужить прощения у семьи.
                     Мощнейший актерский состав под руководством Владимира Меньшова',
			        '1985-01-07', 107,  3);
INSERT INTO FILM (NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
			VALUES ('Один дома',
			        'Новогодняя комедия',
			        '1990-11-10', 103,  1);

INSERT INTO FILM_GENRE (FILM_ID, GENRE_ID) VALUES (1, 1);
INSERT INTO FILM_GENRE (FILM_ID, GENRE_ID) VALUES (1, 2);
INSERT INTO FILM_GENRE (FILM_ID, GENRE_ID) VALUES (2, 6);
INSERT INTO FILM_GENRE (FILM_ID, GENRE_ID) VALUES (4, 1);
INSERT INTO FILM_GENRE (FILM_ID, GENRE_ID) VALUES (5, 1);

INSERT INTO "user"(EMAIL, LOGIN, NAME, BIRTHDAY)
			VALUES ('petr@ussr.ru', 'Petr_USSR', 'Petr', '1970-10-10');
INSERT INTO "user"(EMAIL, LOGIN, NAME, BIRTHDAY)
			VALUES ('leo@yandex.ru', 'leoleo', 'Leonid', '1990-07-15');
INSERT INTO "user"(EMAIL, LOGIN, NAME, BIRTHDAY)
			VALUES ('steve@gmail.com', 'st4', 'Steve', '1998-12-01');

INSERT INTO LIKES (FILM_ID, USER_ID) VALUES (1, 1);
INSERT INTO LIKES (FILM_ID, USER_ID) VALUES (4, 1);
INSERT INTO LIKES (FILM_ID, USER_ID) VALUES (1, 2);
INSERT INTO LIKES (FILM_ID, USER_ID) VALUES (2, 2);
INSERT INTO LIKES (FILM_ID, USER_ID) VALUES (3, 2);
INSERT INTO LIKES (FILM_ID, USER_ID) VALUES (4, 2);
INSERT INTO LIKES (FILM_ID, USER_ID) VALUES (5, 2);
INSERT INTO LIKES (FILM_ID, USER_ID) VALUES (3, 3);

INSERT INTO FRIENDSHIP (USER_ID, FRIEND_ID) VALUES (1, 2);
INSERT INTO FRIENDSHIP (USER_ID, FRIEND_ID) VALUES (2, 1);
INSERT INTO FRIENDSHIP (USER_ID, FRIEND_ID) VALUES (2, 3);
INSERT INTO FRIENDSHIP (USER_ID, FRIEND_ID) VALUES (1, 3);
INSERT INTO FRIENDSHIP (USER_ID, FRIEND_ID) VALUES (3, 1);
*/