INSERT INTO RAITING(NAME) VALUES ('G');
INSERT INTO RAITING(NAME) VALUES ('PG');
INSERT INTO RAITING(NAME) VALUES ('PG-13');
INSERT INTO RAITING(NAME) VALUES ('R');
INSERT INTO RAITING(NAME) VALUES ('NC-17');

SELECT * FROM RAITING r 